name: slash-command

on:
  issue_comment:
    types: [created]

jobs:
  # This is the dispatch for slash commands in the repo
  slash_command:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        id: slash_command
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.GitHubActionsPAT }}
          reaction-token: ${{ secrets.GitHubActionsPAT }}
          commands: deploy
          reactions: dispatched
          permission: write
          issue-type: pull-request
