name: slash_command

on:
  issue_comment:
    types: [created]

jobs:
  # This is the dispatch for slash commands in the repo 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
  slash_command:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: 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
          reaction-token: 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
          commands: deploy
          reactions: dispatched
          permission: write
          issue-type: pull-request
